#!/usr/bin/env node
/**
 * What is actually covered, per skill, right now.
 *
 *     npm run coverage:report
 *     npm run coverage:report -- --check   # fail if docs/test-coverage.md is stale
 *
 * Reads the real state — Tier 3 corpus, Tier 3 behaviour results, Tier 4
 * scenarios, fixture availability — rather than a hand-maintained table. A
 * coverage document that is written by hand becomes a coverage document that is
 * wrong, and a wrong one is worse than none because it is quoted in reviews.
 */
import fs from 'node:fs';
import path from 'node:path';
import { REPO_ROOT, listSkills } from '../test/helpers/repo.mjs';

const skills = listSkills().map((s) => s.dirName);

function readJsonOr(p, fallback) {
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch {
    return fallback;
  }
}

const corpus = readJsonOr(path.join(REPO_ROOT, 'test/tier3/corpus/triggers.json'), { cases: [] });
const triggerResults = readJsonOr(path.join(REPO_ROOT, 'test/tier3/results/latest.json'), null);
const behaviorResults = readJsonOr(path.join(REPO_ROOT, 'test/tier3/results/behavior.json'), null);
const scenariosFile = readJsonOr(path.join(REPO_ROOT, 'test/tier3/scenarios.json'), { scenarios: [] });

let tier4Scenarios = [];
try {
  const src = fs.readFileSync(path.join(REPO_ROOT, 'test/tier4/integration.test.mjs'), 'utf8');
  tier4Scenarios = [...src.matchAll(/skill:\s*'([^']+)'/g)].map((m) => m[1]);
} catch {
  /* tier 4 not present */
}

const fixturesDir = path.join(REPO_ROOT, 'fixtures');
const builtFixtures = fs.existsSync(fixturesDir)
  ? fs.readdirSync(fixturesDir, { withFileTypes: true }).filter((e) => e.isDirectory()).map((e) => e.name)
  : [];

const rows = skills.map((name) => {
  const tier3Cases = corpus.cases.filter((c) => c.expect === name).length;
  const tier4 = tier4Scenarios.filter((s) => s === name).length;
  const recall = triggerResults?.scores?.perSkill?.[name]?.recall;
  const precision = triggerResults?.scores?.perSkill?.[name]?.precision;
  return { name, tier3Cases, tier4, precision, recall };
});

const behaviourBy = {
  safety: (behaviorResults?.results ?? []).filter((r) => r.group === 'safety'),
  injection: (behaviorResults?.results ?? []).filter((r) => r.group === 'injection'),
};

const lines = [];
const pct = (x) => (x === undefined ? '—' : `${(x * 100).toFixed(0)}%`);

lines.push('| Skill | Tier 3 cases | precision | recall | Tier 4 scenarios | verified by execution |');
lines.push('| :--- | ---: | ---: | ---: | ---: | :--- |');
for (const r of rows) {
  const executed = r.tier4 > 0 ? 'yes' : 'no — trigger selection only';
  lines.push(`| \`${r.name}\` | ${r.tier3Cases} | ${pct(r.precision)} | ${pct(r.recall)} | ${r.tier4} | ${executed} |`);
}

const unverified = rows.filter((r) => r.tier4 === 0).map((r) => r.name);

const report = [
  '## Coverage, generated',
  '',
  `Generated by \`npm run coverage:report\` on ${new Date().toISOString().slice(0, 10)}.`,
  'Do not edit this section by hand — it is regenerated and any manual edit is lost.',
  '',
  ...lines,
  '',
  '### Tier 3 behaviour',
  '',
  behaviorResults
    ? `${behaviourBy.safety.filter((r) => r.passed).length}/${behaviourBy.safety.length} safety scenarios pass, ` +
      `${behaviourBy.injection.filter((r) => r.passed).length}/${behaviourBy.injection.length} injection scenarios pass ` +
      `(measured ${behaviorResults.generatedOn.slice(0, 10)} on ${behaviorResults.model}` +
      `${behaviorResults.withNegativeControl ? ', with negative controls' : ', WITHOUT negative controls'}).`
    : `Not measured. ${scenariosFile.scenarios.length} scenarios are defined; run \`npm run evals:behavior\`.`,
  '',
  '### Tier 4 fixtures',
  '',
  builtFixtures.length
    ? `Built locally: ${builtFixtures.join(', ')}.`
    : 'None built locally. Tier 4 scenarios skip with the command that would build them.',
  '',
  '### Skills with no execution-backed scenario',
  '',
  unverified.length
    ? unverified.map((n) => `- \`${n}\` — covered by Tier 3 trigger selection only. Its **procedure** has not been executed against a real Backstage repository.`).join('\n')
    : 'None.',
  '',
];

const text = report.join('\n');

if (process.argv.includes('--check')) {
  const docPath = path.join(REPO_ROOT, 'docs', 'test-coverage.md');
  const doc = fs.existsSync(docPath) ? fs.readFileSync(docPath, 'utf8') : '';
  const missing = skills.filter((n) => !doc.includes(n));
  if (missing.length) {
    console.error(`docs/test-coverage.md does not mention: ${missing.join(', ')}`);
    process.exit(1);
  }
  console.log('docs/test-coverage.md mentions every skill.');
  process.exit(0);
}

console.log(text);
